# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rpipe}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristopher Kosmatka", "Erik Kastman"]
  s.date = %q{2010-05-24}
  s.description = %q{Neuroimaging preprocessing the Ruby way}
  s.email = %q{kjkosmatka@gmail.com}
  s.executables = ["rpipe", "swallow_batch_run.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rpipe",
     "bin/swallow_batch_run.rb",
     "lib/custom_methods/Merit220Preproc.m",
     "lib/custom_methods/Merit220Preproc.rb",
     "lib/custom_methods/Merit220Preproc_job.m",
     "lib/custom_methods/ReconWithHello.rb",
     "lib/default_preproc.rb",
     "lib/default_recon.rb",
     "lib/default_stats.rb",
     "lib/rpipe.rb",
     "lib/trollop.rb",
     "rpipe.gemspec",
     "test/drivers/mrt00015.yml",
     "test/drivers/mrt00015_hello.yml",
     "test/drivers/tmp.yml",
     "test/helper.rb",
     "test/test_dynamic_method_inclusion.rb",
     "test/test_includes.rb",
     "test/test_johnson.merit220.visit1_preproc.rb",
     "test/test_preproc.rb",
     "test/test_recon.rb",
     "test/test_rpipe.rb"
  ]
  s.homepage = %q{http://github.com/brainmap/rpipe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Neuroimaging preprocessing the Ruby way}
  s.test_files = [
    "test/helper.rb",
     "test/test_dynamic_method_inclusion.rb",
     "test/test_includes.rb",
     "test/test_johnson.merit220.visit1_preproc.rb",
     "test/test_preproc.rb",
     "test/test_recon.rb",
     "test/test_rpipe.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

